### ISSUE TITLE
Multiple Errors

### ISSUE THREAD

**Issue by EnArvy** [nhanb/mpv-gdrive#2]
D:\Installations\mpv>mpv gdrive://1KgxbqgqrPeotbmikZy_hLU6yYh_4kbKb
[gdrive] Loading GDrive script
[gdrive] Detected google drive link, rewriting stream-open-filename
[gdrive] Requesting token for client_id fill-me[...]
[gdrive]
[gdrive] stack traceback:
[gdrive]        [string "C:\Users\darkl\AppData\Roaming/mpv/scripts/gd..."]:21: in function 'fn'
[gdrive]        mp.defaults:579: in function 'handler'
[gdrive]        mp.defaults:500: in function 'call_event_handlers'
[gdrive]        mp.defaults:534: in function 'dispatch_events'
[gdrive]        mp.defaults:493: in function <mp.defaults:492>
[gdrive]        [C]: at 0x00852de0
[gdrive]        [C]: at 0x008517f0
[gdrive] Lua error: [string "C:\Users\darkl\AppData\Roaming/mpv/scripts/gd..."]:112: attempt to index global 'access_token' (a nil value)
client removed during hook handling
[ffmpeg] https: HTTP error 403 Forbidden
Failed to open https://www.googleapis.com/drive/v3/files/1KgxbqgqrPeotbmikZy_hLU6yYh_4kbKb?alt=media.
[ytdl_hook]
[ytdl_hook] youtube-dl failed: not found or not enough permissions
[ffmpeg] https: HTTP error 403 Forbidden
Failed to open https://www.googleapis.com/drive/v3/files/1KgxbqgqrPeotbmikZy_hLU6yYh_4kbKb?alt=media.

Exiting... (Errors when loading file)

**Comment by EnArvy** [comment]
Nvm better mention in readme about needing to fill access token Im stupid

**Comment by nhanb** [comment]
Hey @EnArvy thanks for the suggestion, I added that in the README: https://github.com/nhanb/mpv-gdrive/commit/956fd82d7cb9edb71bf6201e8b6305b88aede8a4

I'm glad it worked out for you.
