### ISSUE TITLE
[Question] How to get the entries in gdrive.conf?

### ISSUE THREAD

**Issue by WhoMI7** [nhanb/mpv-gdrive#3]
gdrive_client_id=fill-me
gdrive_client_secret=fill-me
gdrive_refresh_token=fill-me

Where do I get these?

**Comment by nhanb** [comment]
The client ID & secret you'll need to create from the google developer console. You'll then need to use those to authorize via oauth to get the refresh_token for you google account. Have a look at [rclone's guide](https://rclone.org/drive/) for more clues. Better yet, you can use `rclone config` to get the refresh_token for you.

**Comment by WhoMI7** [comment]
I did all of that but I am getting an error:




[gdrive] Loading GDrive script
[gdrive] Detected google drive link, rewriting stream-open-filename
[gdrive] Requesting token for client_id 2844025687[...]
[gdrive]
[gdrive] stack traceback:
[gdrive]        [string "C:\Users\BHATURA\AppData\Roaming/mpv/scripts/g..."]:20: in function 'fn'
[gdrive]        mp.defaults:597: in function 'handler'
[gdrive]        mp.defaults:510: in function 'call_event_handlers'
[gdrive]        mp.defaults:552: in function 'dispatch_events'
[gdrive]        mp.defaults:503: in function <mp.defaults:502>
[gdrive]        [C]: at 0x7ff67c3a3310
[gdrive]        [C]: at 0x7ff67c3a1590
[gdrive] Lua error: [string "C:\Users\BHATURA\AppData\Roaming/mpv/scripts/g..."]:111: attempt to index global 'access_token' (a nil value)
client removed during hook handling
[08:35:18 INF] Connected to MPV
[08:35:18 INF] MPV Connection started
[08:35:18 INF] Event handling set
[ffmpeg] https: HTTP error 403 Forbidden
Failed to open https://www.googleapis.com/drive/v3/files/16rElExvQzD93y2tyrSV4pQC5pTwRTYUu?alt=media.
[ytdl_hook] ERROR: [generic] Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output. (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
[ytdl_hook] youtube-dl failed: unexpected error occurred
[ffmpeg] https: HTTP error 403 Forbidden
Failed to open https://www.googleapis.com/drive/v3/files/16rElExvQzD93y2tyrSV4pQC5pTwRTYUu?alt=media.

Exiting... (Errors when loading file)
[08:35:24 INF] MPV Disconnected

**Comment by nhanb** [comment]
Worked on my machine (tm):

![image](https://user-images.githubusercontent.com/1446315/154384598-506890d5-2062-4a96-81c0-089f0f85790c.png)

Your logs say that it couldn't retrieve an access_token from google api, meaning your credentials (client_id, client_secret, refresh_token) weren't correct. Remember you're supposed to put the filled out conf file in `$HOME/.config/mpv/script-opts/`, and you need to fill out all 3 fields.

**Comment by nhanb** [comment]
Oh and remember to check that you have `curl` installed.

**Comment by WhoMI7** [comment]
Can you please provide a guide or a tutorial on how to get "client_id, client_secret, refresh_token" I tried several times but it isn't working

**Comment by nhanb** [comment]
Here's another guide from Google: https://developers.google.com/workspace/guides/create-credentials#oauth-client-id - Just remember to pick the Desktop application type. You'll receive client_id and client_secret.

Then, again, follow the steps in rclone instructions: https://rclone.org/drive/
```sh
No remotes found - make a new one
n) New remote
r) Rename remote
c) Copy remote
s) Set configuration password
q) Quit config
n/r/c/s/q> n
name> remote
Type of storage to configure.
Choose a number from below, or type in your own value
[snip]
XX / Google Drive
   \ "drive"
[snip]
Storage> drive
Google Application Client Id - leave blank normally.
client_id>
Google Application Client Secret - leave blank normally.
client_secret>
Scope that rclone should use when requesting access from drive.
Choose a number from below, or type in your own value
 1 / Full access all files, excluding Application Data Folder.
   \ "drive"
 2 / Read-only access to file metadata and file contents.
   \ "drive.readonly"
   / Access to files created by rclone only.
 3 | These are visible in the drive website.
   | File authorization is revoked when the user deauthorizes the app.
   \ "drive.file"
   / Allows read and write access to the Application Data folder.
 4 | This is not visible in the drive website.
   \ "drive.appfolder"
   / Allows read-only access to file metadata but
 5 | does not allow any access to read or download file content.
   \ "drive.metadata.readonly"
scope> 1
ID of the root folder - leave blank normally.  Fill in to access "Computers" folders. (see docs).
root_folder_id> 
Service Account Credentials JSON file path - needed only if you want use SA instead of interactive login.
service_account_file>
Remote config
Use auto config?
 * Say Y if not sure
 * Say N if you are working on a remote or headless machine or Y didn't work
y) Yes
n) No
y/n> y
If your browser doesn't open automatically go to the following link: http://127.0.0.1:53682/auth
Log in and authorize rclone for access
Waiting for code...
Got code
Configure this as a Shared Drive (Team Drive)?
y) Yes
n) No
y/n> n
--------------------
[remote]
client_id = 
client_secret = 
scope = drive
root_folder_id = 
service_account_file =
token = {"access_token":"XXX","token_type":"Bearer","refresh_token":"XXX","expiry":"2014-03-16T13:57:58.955387075Z"}
--------------------
y) Yes this is OK
e) Edit this remote
d) Delete this remote
y/e/d> y
```

... during which it will automatically open a browser tab that asks you to authenticate using your google account. Do that.

Notice how the last prompt has this line:

```
token = {"access_token":"XXX","token_type":"Bearer","refresh_token":"XXX","expiry":"2014-03-16T13:57:58.955387075Z"}
```

You only need to look at the `"refresh_token":"XXX"` part, where XXX is your `refresh_token`.

To verify that the 3 values work, try running this curl command (replace XXX with your credentials of course):

```sh
curl --location --request POST 'https://www.googleapis.com/oauth2/v4/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'client_id=XXX' \
--data-urlencode 'client_secret=XXX' \
--data-urlencode 'refresh_token=XXX' \
--data-urlencode 'grant_type=refresh_token'
```

If they're valid you'll get a response like this:
```json
{
    "access_token": "long long string",
    "expires_in": 3599,
    "scope": "https://www.googleapis.com/auth/drive.readonly",
    "token_type": "Bearer"
}
```

**Comment by WhoMI7** [comment]
It's beyond me at this point. Let's just close it.
