### ISSUE TITLE
qutebrowser instead of extension

### ISSUE THREAD

**Issue by Spuxy** [nhanb/mpv-gdrive#4]
Hello i did not install yet ur script but it would be better make some py script for qutebrowser to extract id of file. 
I know its limited cause a lot of ppl use firefox but the integration with qutebrowser would be awesome

**Comment by nhanb** [comment]
Hey thanks for checking this out @Spuxy. Unfortunately I don't use qutebrowser so I'm not going to explicitly support that any time soon.

On the other hand, I'm not sure why you can't use my provided userscript as-is. AFAIK qutebrowser [does support](https://qutebrowser.org/FAQ.html) greasemonkey scripts, doesn't it?

> How do I make qutebrowser use greasemonkey scripts?
>
> There is currently no UI elements to handle managing greasemonkey scripts. All management of what scripts are installed or disabled is done in the filesystem by you. qutebrowser reads all files that have an extension of .js from the <data>/greasemonkey/ folder and attempts to load them. Where <data> is the qutebrowser data directory shown in the Paths section of the page displayed by :version. If you want to disable a script just rename it, for example, to have .disabled on the end, after the .js extension. To reload scripts from that directory run the command :greasemonkey-reload.
